models/character.py
from sqlalchemy import *
from extentions import db

class Character(db.Model):
    id = Column(Integer , primary_key=True)
    name = Column(String(100) , nullable=False)
    desc = Column(Text , nullable=False)
    image_thumb = Column(String, nullable=False)
    image_full = Column(String , nullable=False)
    slug = Column(String(50) , unique=True , nullable=False)

models/story.py
from sqlalchemy import *
from extentions import db


class Story(db.Model):
    __tablename__ = "stories"
    id = Column(Integer , primary_key=True)
    title = Column(String(255),nullable=False)
    desc = Column(Text , nullable=True)
    slug = Column(String(255), unique=True , nullable=False)


    parts = db.relationship("StoryPart" , backref = "story" , cascade ="all,delete-orphan")

class StoryPart(db.Model) :
    __tablename__ = "story_parts"
    id = Column(Integer , primary_key=True)
    title = Column(String(255),nullable=False)
    content = Column(Text , nullable=False)

    story_id = Column(Integer , ForeignKey("stories.id") , nullable=False)

app.py
from flask import Flask
from blueprints.general import app as general
from blueprints.admin import app as admin
from extentions import *
from config import *
from models.story import Story
from flask_wtf.csrf import CSRFProtect


app = Flask(__name__)
app.register_blueprint(general)
app.register_blueprint(admin)

app.secret_key = SECRET_KEY
csrf = CSRFProtect(app)

app.config["SQLALCHEMY_DATABASE_URI"] = SQLALCHEMY_DATABASE_URI
db.init_app(app)


with app.app_context():
    db.create_all()

if __name__ ==  '__main__':
    app.run(debug=True , port= 8089)

blueprints/admin.py
from flask import Blueprint ,current_app, render_template , redirect , request , url_for , flash
import json , os
from models.story import Story , StoryPart
from models.character import Character
from extentions import *
import uuid

app = Blueprint('admin' , __name__ , url_prefix="/admin")


@app.route("/dashboard")
def dashboard():
    stories = Story.query.all()
    return render_template("admin/dashboard.html" , stories = stories)


@app.route("/new-story" , methods = ["POST"])
def new_story():
        title = request.form["title"]
        desc = request.form["desc"]
        slug = str(uuid.uuid4())[:8]


        story = Story(title = title , desc = desc , slug = slug)
        db.session.add(story)
        db.session.commit()
        flash("داستان اضافه شد ")
        return redirect(url_for("admin.dashboard"))
    

@app.route("/new-part/<int:story_id>" , methods = ["POST"])
def new_part(story_id):
    
        title = request.form["title"]
        content = request.form["content"]
        part = StoryPart(title = title , content = content , story_id = story_id)
        db.session.add(part)
        db. session.commit()
        
        flash("قسمت جدید اضافه شد ")
        return redirect(url_for("admin.dashboard"))
   


@app.route("/story/delete/<int:story_id>" , methods = ["POST"])
def delete_story(story_id):
       story = Story.query.get_or_404(story_id)
       db.session.delete(story)
       db.session.commit()
       flash('داستان حذف شد')
       return redirect(url_for("admin.dashboard"))



@app.route("/story/edit/<int:story_id>" , methods = ["GET" , "POST"])
def edit_story(story_id):
       story = Story.query.get_or_404(story_id)
       if request.method == "POST":
              story.title = request.form["title"]
              story.desc = request.form["desc"]
              db.session.commit()
              flash("داستان ویرایش شد ")
              return redirect(url_for("admin.dashboard"))
       return render_template("admin/edit_story.html" , story = story)




@app.route("/part/delete/<int:part_id>" , methods = ["POST"])
def delete_part(part_id):
       part = StoryPart.query.get_or_404(part_id)
       story_id = part.story_id
       db.session.delete(part)
       db.session.commit()
       flash("قسمت حذف شد")
       return redirect (url_for("admin.dashboard"))




@app.route("/part/edit/<int:part_id>" , methods = ["GET" , "POST"])
def edit_part(part_id):
       part = StoryPart.query.get_or_404(part_id)
       if request.method == "POST":
              part.title = request.form["title"]
              part.content = request.form["content"]
              db.session.commit()
              flash("قسمت ویرایش شد ")
              return redirect(url_for("admin.dashboard"))
       return render_template("admin/edit_part.html" , part = part)




@app.route('/characters')
def characters():
       chars = Character.query.all()
       return render_template("admin/characters.html" , chars = chars)



@app.route("/character/new" , methods = ["GET" , "POST"])
def new_character():
       if request.method == "POST":
              name = request.form["name"]
              desc = request.form["desc"]
              thumb = request.files["thumb"]
              full = request.files["full"]

              slug = str(uuid.uuid4())[:8]

              thumb_filename = f"{slug}_thumb.jpg"
              full_filename = f"{slug}_full.jpg"

              thumb.save(os.path.join(current_app.static_folder,"images/gallery/thumbs"  , thumb_filename))
              full.save(os.path.join(current_app.static_folder,"images/gallery/fulls" , full_filename))

              char = Character(
                     name = name,
                     desc = desc,
                     image_thumb = f"images/gallery/thumbs/{thumb_filename}",
                     image_full = f"images/gallery/fulls/{full_filename}",
                     slug = slug ,
              )

              db.session.add(char)
              db.session.commit()
              flash("شخصیت جدید اضافه شد")
              return redirect(url_for("admin.characters"))

       return render_template("admin/new_character.html")


@app.route("/character/delete/<int:char_id>" , methods =["POST"])
def delete_character(char_id):
       char = Character.query.get_or_404(char_id)
       db.session.delete(char)
       db.session.commit()
       flash("شخصیت حذف شد")
       return redirect(url_for("admin.characters"))

blueprints/general.py
from flask import Blueprint , render_template , abort
import json
from models.story import Story ,StoryPart
from models.character import Character


app = Blueprint('general' , __name__)


@app.route("/")
def main ():
    stories = Story.query.all()
    characters = Character.query.all()
    return render_template("main.html" , stories = stories , characters = characters)


@app.route("/stories")
def story_list():
    stories = Story.query.all()
    return render_template("story_list.html" , stories = stories)

@app.route("/story/<slug>")
def story_detail(slug):
    story = Story.query.filter_by(slug = slug).first_or_404()
    return render_template("story_detail.html" , story = story)


@app.route("/story/<slug>/part/<int:part_id>")
def story_part(slug,part_id):
    story = Story.query.filter_by(slug = slug).first_or_404()
    part = StoryPart.query.get_or_404(part_id)

    if part.story_id != story.id:
        abort(404)
    
    next_part = StoryPart.query.filter(StoryPart.story_id == story.id , StoryPart.id > part.id).order_by(StoryPart.id.asc()).first()
    prev_part = StoryPart.query.filter(StoryPart.story_id == story.id , StoryPart.id < part.id).order_by(StoryPart.id.desc()).first()

    all_parts = StoryPart.query.filter_by(story_id = story.id).order_by(StoryPart.id.asc()).all()

    return render_template("story_part.html" , story = story , part = part , next_part = next_part , prev_part = prev_part , all_parts = all_parts)



@app.route("/character/<slug>")
def character_detail(slug):
    char = Character.query.filter_by(slug = slug).first_or_404()
    return render_template("character_detail.html" , char = char)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/index.css')}}">
    {% block header %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
    <script src="/static/js/scripts.js"></script>
</body>
</html>

templates/character_detail.html
{% extends 'base.html' %}

{% block header %}
    <title>{{ char.name }}</title>
    	<meta charset="utf-8" dir="rtl" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/main.css' ) }}" />
		<noscript><link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/noscript.css' ) }}" /></noscript>

{% endblock %}

{% block body %}
<section class="simple-box">
    <h2>{{ char.name }}</h2>
    <img src="{{ url_for('static' , filename = char.image_full) }}" style="max-width: 400px;">
    <p>{{ char.desc }}</p>
    <a href="{{ url_for('general.main') }}">بازگشت</a>
    </section>

    	<script src="{{ url_for('static' , filename = 'assets/js/jquery.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrollex.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrolly.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/browser.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/breakpoints.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/util.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/main.js') }}"></script>

        
{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% block header %}
<title>داستان</title>
		<meta charset="utf-8" dir="rtl" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/main.css' ) }}" />
		<noscript><link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/noscript.css' ) }}" /></noscript>

{% endblock %}
{% block body %}
<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper" class="divided">

				<!-- One -->
					<section class="banner style1 orient-left content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
						<div class="content">
							<h1>داستان فرعی(بی اسم)</h1>
							<p class="major">این یکی از داستانهای آتنا و فریباست که <strong >شاید</strong> ادامه بدن.</p>
							{% if stories %}
							<ul class="actions stacked">
								{% for story in stories %}
								<li><a href="{{ url_for('general.story_detail' , slug = story.slug) }}" class="button big wide smooth-scroll-middle">{{ story.title }}</a></li>
								{% endfor %}
							</ul>
							{% else %}
							<p>هنوز هیچ داستانی اضافه نشده</p>
							{% endif %}
						</div>
						<div class="image">
							<img src="{{ url_for('static' , filename = 'images/banner.jpg') }}" alt="" />
						</div>
					</section>

				<!-- Two -->
					<section class="spotlight style1 orient-right content-align-left image-position-center onscroll-image-fade-in" id="first">
						<div class="content">
							<section class="simple-box" >
                                <section class="question-box" >
                                    <h4>این سایت چه کمکی به من میکنه؟</h4>
                                    <p>این سوال همونقدر احمقانست که بگی اینستا چه کمکی بهم میکنه ولی خب جوابشو میدم، گذروندن وقت</p>
                                </section>
                                <section class="question-box" >
                                    <h4>چرا باید این سایتو انتخاب کنم؟</h4>
                                    <p>چون از حق نگذریم خوب مینویسیم</p>
                                </section>
                                <section class="question-box" >
                                    <h4>میتونیم خودمون هم توی نوشتن داستان نقشی داشته باشیم؟ </h4>
                                    <p>صد البته!البته هنوز این بخشو نساختم بعدا تو اپدیتای بعدی شاید</p>
  
                                </section>
                            </section>
						</div>
						<div class="image">
							<img src="{{ url_for('static' , filename = 'images/spotlight01.jpg') }}" alt="" />
						</div>
					</section>

				

				<!-- Five -->
					<section class="wrapper style1 align-center">
						<div class="inner">
							<h2>شخصیت ها</h2>
							<p>در این پنل میتونی شخصیت هارو ببینی اگه اطلاعات بیشتر میخوای روشون کلیک کن</p>
						</div>

						<!-- Gallery -->
							<div class="gallery style2 medium lightbox onscroll-fade-in">
								{% for c in characters %}
								<article>
									<a href="{{ url_for('static' , filename = c.image_full) }}" class="image">
										<img src="{{ url_for('static' , filename = c.image_thumb) }}" alt="{{ c.name }}">
									</a>
									<div class="caption">
										<h3>{{ c.name }}</h3>
										<p>{{ c.desc[:100] }}</p>
										<ul class="actions fixed">
											<li><a href="{{ url_for('general.character_detail' , slug = c.slug) }}" class="button small">جزئیات بیشتر</a></li>
										</ul>
									</div>
								</article>
							    {% endfor %}
							</div>

					</section>

				<!-- Footer -->
					<footer class="wrapper style1 align-center">
						<div class="inner">
							<ul class="icons">
								<li><a href="#" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
								<li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
								<li><a href="#" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
								<li><a href="#" class="icon brands style2 fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
								<li><a href="#" class="icon style2 fa-envelope"><span class="label">Email</span></a></li>
							</ul>
							<p>&copy; Untitled. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrollex.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrolly.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/browser.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/breakpoints.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/util.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/main.js') }}"></script>

	</body>


{% endblock %}

templates/story_detail.html
{% extends 'base.html' %}

{% block header %}
    <title>{{ story.title }}</title>
      <meta charset="utf-8" dir="rtl" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/main.css' ) }}" />
		<noscript><link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/noscript.css' ) }}" /></noscript>

{% endblock %}

{% block body %}
<section class="simple-box">
    <h2>{{ story.title }}</h2>
    <p>{{ story.desc }}</p>

    <h3>قسمت ها :</h3>
    <ul>
        {% for part in story.parts %}
                <a href="{{ url_for('general.story_part' , slug = story.slug , part_id = part.id) }}">{{ part.title }}</a> <br>
        {% else %}
            <li>هیچ قسمتی نوشته نشده</li>
        {% endfor %}
    </ul>
</section>
    <script src="{{ url_for('static' , filename = 'assets/js/jquery.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrollex.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrolly.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/browser.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/breakpoints.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/util.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/main.js') }}"></script>
{% endblock %}

templates/story_list.html
{% extends 'base.html' %}

{% block header %}
    <title>داستان ها </title>
{% endblock %}

{% block body %}
    <h2>داستان ها</h2>
    <ul>
        {% for story in stories %}
            <li>
                <a href="{{ url_for('general.story_detail' , slug = story.slug) }}">{{ story.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/story_part.html
{% extends 'base.html' %}

{% block header %}
    <title>{{ story.title }}</title>
    <meta charset="utf-8" dir="rtl" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/main.css' ) }}" />
		<noscript><link rel="stylesheet" href="{{ url_for('static' , filename = 'assets/css/noscript.css' ) }}" /></noscript>

{% endblock %}

{% block body %}
<section class="simple-box">
    <h2>{{ story.title }}</h2>
    <h3>{{ part.title }}</h3>
    <div style="white-space: pre-line; text-align: justify;">
        {{ part.content }}
    </div>
<div style="margin-top: 20px;">
    {% if prev_part %}
        <a href="{{ url_for('general.story_part' , slug = story.slug , part_id = prev_part.id) }}" class="button">قسمت قبلی</a>
    {% endif %}

    {% if next_part %}
    <a href="{{ url_for('general.story_part' , slug = story.slug , part_id = next_part.id) }}" class="button">قسمت بعدی</a>
    {% endif %}
    
</div>
</section>
<hr>
<h4>رفتن به قسمت خاص</h4>
<form method="get" action="">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <select onchange="location = this.value;">
        {% for p in all_parts %}
        <option value="{{ url_for('general.story_part' , slug = story.slug , part_id = p.id) }}" {% if p.id == part.id %}selected{% endif %}>
            {{ p.title }}
        </option>
        {% endfor %}
    </select>
</form>

<script src="{{ url_for('static' , filename = 'assets/js/jquery.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrollex.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/jquery.scrolly.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/browser.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/breakpoints.min.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/util.js') }}"></script>
			<script src="{{ url_for('static' , filename = 'assets/js/main.js') }}"></script>
{% endblock %}